api:
  geocoding: "https://geocoding-api.open-meteo.com/v1/search"
  weather: "https://api.open-meteo.com/v1/forecast"
  weatherForecast: "https://api.open-meteo.com/v1/forecast?hourly=temperature_2m&hourly=windspeed_10m&hourly=rain"
  reverseGeocoding: "https://nominatim.openstreetmap.org/reverse?format=json&zoom=10&accept-language=en"
  time: "https://www.timeapi.io/api/Time/current/coordinate"
  weatherForecastSpecificDay: "https://api.open-meteo.com/v1/forecast?daily=weathercode,temperature_2m_max,temperature_2m_min,windspeed_10m_max&timezone=Europe/Berlin"
  openAI: "https://api.openai.com/v1/completions"

token:
  openAIToken: "Bearer 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"

spring:
  datasource:
    url: jdbc:h2:mem:demo_db
    driver-class-name: org.h2.Driver
    username: umbrella
    password: umbrella
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true

umbrella:
  app:
    jwtCookieName: umbrellaCorporation
    jwtSecret: 357638792F423F4528482B4B6250655368566D597133743677397A2443264629
    jwtExpirationMs: 86400000
